---
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -w -s
        -X github.com/prometheus/common/version.Version={{ .Version }}
        -X github.com/prometheus/common/version.Revision={{ .Commit }}
        -X github.com/prometheus/common/version.Branch={{ .Branch }}
        -X github.com/prometheus/common/version.BuildUser=greenpau
        -X github.com/prometheus/common/version.BuildDate={{ .Date }}
        -X github.com/greenpau/ovs_exporter/pkg/ovs_exporter.appVersion={{ .Version }}
        -X github.com/greenpau/ovs_exporter/pkg/ovs_exporter.gitBranch={{ .Branch }}
        -X github.com/greenpau/ovs_exporter/pkg/ovs_exporter.gitCommit={{ .Commit }}
        -X github.com/greenpau/ovs_exporter/pkg/ovs_exporter.buildUser=greenpau
        -X github.com/greenpau/ovs_exporter/pkg/ovs_exporter.buildDate={{ .Date }}
    main: './cmd/ovs_exporter'
    asmflags:
      - 'all=-trimpath={{.Env.GOPATH}}'
    gcflags:
      - 'all=-trimpath={{.Env.GOPATH}}'
    binary: ovs-exporter
archives:
  - name_template: "ovs-exporter_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
